import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <nav>
            <img src="/oPronouns-logo.svg" className="nav-img"/> 
        <Link href="/" className={"active"} passHref>openPronouns</Link>
        <ul className="nav-list">
            <li className="nav-list"><a href="/wiki">Wiki</a></li>
        </ul>
      </nav>

      <main>
        <div className="container hero">
          <img src="/pronouns-en.png" alt="hero image"/>
          <h1>openPronouns</h1>
        </div>
      </main>
      </div>
    </>
  )
}
