import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import toTitleCase from '../lib/title_case';
import {
  useTranslation,
  useLanguageQuery,
  LanguageSwitcher,
} from "next-export-i18n";

export default function Home() {
  const { t } = useTranslation();
  const [query] = useLanguageQuery();
  
  return (
    <>
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <nav>
            <img src="/oPronouns-logo.svg" className="nav-img"/> 
        <Link href="/" className={"active"} passHref>openPronouns</Link>
        <ul className="nav-list">
            <li className="nav-list"><Link href="/wiki">{toTitleCase(t("global.wiki"))}</Link></li>
        </ul>
      </nav>

      <main>
        <div className="container hero">
          <img src="/pronouns-en.png" alt="hero image"/>
          <h1>openPronouns</h1>
        </div>
      </main>
      </div>
    </>
  )
}
