import Head from "next/head";

export default function WikiIpfs() {
    return (
        <>
            <div>
                <Head>
                    <title>openPronouns {toTitleCase(t('global.wiki'))}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/oPronouns-logo.svg" type="image/svg" />
                </Head>
            </div>
        </>
    )
}